### ISSUE TITLE
poll module error

### ISSUE THREAD

**Issue by LeoAlt8** [weidengeist/Willowbot#13]
Hello. When using the command:

```
  "!poll" : {
    'matchType' : 'startsWith',
    'debug'     : 'Poll has been started.',
    'function'  : ['poll_start(commands, irc, "$arg0+")'],
    "minLevel"  : 3
    },
```
I get errors:
```
Traceback (most recent call last):
  File "D:\Willowbot\main_cli.py", line 78, in <module>
    chatMsg.processCommands(commands, r, irc)
  File "D:\Willowbot\modules\message.py", line 394, in processCommands
    self.reactToMessage(commands, 'general', c, irc)
  File "D:\Willowbot\modules\message.py", line 292, in reactToMessage
    eval(func)
  File "<string>", line 1, in <module>
NameError: name 'p' is not defined
```
and
```
Traceback (most recent call last):
  File "D:\Willowbot\main_cli.py", line 74, in <module>
    checkTimedCommands(commands['timed'], irc)
  File "D:\Willowbot\modules\basics.py", line 310, in checkTimedCommands
    eval(reaction['function'])
  File "<string>", line 1, in <module>
NameError: name 'commands' is not defined. Did you mean: 'getCommands'?
```
Each error stops the bot from working. The poll starts up, but as soon as viewers start chatting, there's a bot error.

Commands are run from an account with the moderator role.

OS: Win11x64
Python: Python 3.11.3

**Comment by weidengeist** [comment]
The most recent change of the `function` key from a string to a list of strings has not been committed to the `poll` module. This has been [fixed](https://github.com/weidengeist/Willowbot/commit/419d2a3623b1b155a58d06264ecb22c13d54c9a0) now and I have successfully tested the `poll` module functionality. Please provide feedback if it solves your problems.

Kind regards,
Weidengeist

**Comment by weidengeist** [comment]
The fix needed here was a little more extensive than I thought. The polls should be fixed now.

Sorry for any inconvenience.

**Comment by weidengeist** [comment]
The first problem – `poll` not registering Cyrillic input – is the result of Willowbot converting Cyrillic letters that look like Latin ones into their Latin counterparts, which has been implemented because scam bots tried to avoid automatic bans by pattern matching. This conversion, however, leads to issues when Willowbot is used in mainly Cyrillic context, so [I made it optional](https://github.com/weidengeist/Willowbot/commit/8035b3e59a1cca69b116bb42b5a10b230a940525#diff-a644f471f85258b78b48f194825de4a7a1b81d813862a2ba56da24eaa89d4c00). The documentation has been [updated accordingly](https://github.com/weidengeist/Willowbot/commit/8035b3e59a1cca69b116bb42b5a10b230a940525#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). In short, you have to add `'cyrillicToLatinConversion : False` to your config file. It should then look like this:
```
config = {
  'botname'                   : '**********',
  'clientID'                  : e5kdpgd2bbnbj1u5gbjpzeq7vsgwup',
  'connectionRetries'         : 10,
  'disconnectCheckInterval'   : 10,
  'port'                      : 6697,
  'server'                    : 'irc.chat.twitch.tv',
  'cyrillicToLatinConversion' : False
}
```
This key will also be added automatically when configuring Willowbot (`python main_cli.py  --configure`), but you certainly won’t want to run through this process for just adding one new key.

I have used your bug report as an opportunity to [redesign the `poll` module](https://github.com/weidengeist/Willowbot/commit/2f63288d1daeba4e59be1316179950a6399986b9#diff-afb30e9c1614df780368a082b9bc976ada9ff29e27810ab8efb5440f64a2939f). The bug you have encountered is fixed now; subsequentially initiated polls will no longer affect each other. Additionally, you may now provide custom output phrases for the `!poll` command without having to modify the module itself. Please see the [updated README](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#42-poll-module) for details. Those changes are designed with backwards compatibility, i.e. your current commands won’t cause an error if you don’t use the module’s new capabilities.

**Comment by weidengeist** [comment]
I have committed a [fix](https://github.com/weidengeist/Willowbot/commit/8e9ad1a7113a963baa7ad420353fcf069279aafe) for that scenario, which will set the poll duration to 60 seconds if the first argument of `!poll` can’t be successfully converted to an integer.

Additionally, I have implemented the ability to [cancel a poll](https://github.com/weidengeist/Willowbot/commit/7c70b7bfc58b7bdab3da15b50078de75ae10d757). The usage of this feature is, of course, [documented in the updated README](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#42-poll-module).

**Comment by weidengeist** [comment]
This command format would be counter-intuitive, because it does not match the way chat commands are usually designed, namely without comma, unless the comma is part of the argument, for example a quote that is added to a stream quote database. Furthermore, poll answers should be as short and as simple as possible to prevent typos and make it easy for the chat to participate. Adapted to the example you posted above, it would be `!poll 60 green red pine` instead.

So it’s a no, I‘m afraid. I’m not going to change the poll argument format, because it would break with the conventions.

**Comment by xlvlx** [comment]
in fact, it is a very interesting command, but it would be more convenient if it were accepted as a comma-separated text, and the answer options were displayed in a list of numbers, otherwise it is not always possible to describe the choice in one word, and write the answer correctly (then the bot does not count)!

**Comment by weidengeist** [comment]
I have redesigned the `poll` module to honor the programming syntax conventions and provide the desired functionality. The module will now accept quoted strings as answer options. Polls can now be started like `!poll 60 "Dark Souls" "Elden Ring"`. Additionally, the chat will be able to vote by typing the number corresponding the answer option instead of having to type the full answer option. Please see [the `poll` module section](https://github.com/weidengeist/Willowbot#42-poll-module) in the README for important changes and details.

**Comment by xlvlx** [comment]
Good afternoon! 
1) Is it possible to somehow limit the "gratitude to the streamer" so that the command works from 3 raiders or more, otherwise jokers sometimes throw raids and notify them?
2) how to limit the input of numbers greater than 9 in the "randomIntegers module", otherwise you can put a number up to 151 and a long message occurs in the chat!
3) you can combine the result message in the "poll module", otherwise my streamer scolds me for spamming messages ((or at least remove the zero forecast!

**Comment by weidengeist** [comment]
1. Please do not discuss `randomIntegers` in an issue about the `poll` module. Keep the discussions clean for everyone to look up topic easily. However, to answer your question: Use Python’s `min(…)` method to limit the amount of generated numbers. I have [updated the README](https://github.com/weidengeist/Willowbot#45-randomIntegers-module) to describe that briefly.
2. I have added the parameter `votesResultDelimiter` to the `poll_start()` routine. Please read [the updated documentation](https://github.com/weidengeist/Willowbot?tab=readme-ov-file#42-poll-module) to know its effects and how to use it.
