### ISSUE TITLE
Error "needsVIP"  : true"

### ISSUE THREAD

**Issue by LeoAlt8** [weidengeist/Willowbot#7]
![2022-12-03](https://user-images.githubusercontent.com/92355871/205399644-0a0a5747-fcbf-4a67-8ec9-a8221d640174.png)

Error occurs after adding command:

`"!!аз" : {
"answer" : "Това действие е достъпно само за вас. Така че получавате милион сърца bleedPurple bleedPurple bleedPurple  ",
"cooldown" : 30,
"needsVIP"  : true`

**Comment by weidengeist** [comment]
`needsVIP` expects a boolean value and those have a capital first letter in Python: `True`, not `true`. If you use the latter, Python expects it to be a variable and tries to evaluate it, which will fail, because you have not defined `true`. Depending on your IDE (hopefully, you don’t write Python code in a simple text editor), you should see a difference between `true` and `True` in the syntax highlighting of the IDE.

**Comment by weidengeist** [comment]
Thanks for pointing this out. The typo in the manual has been fixed now.

Additionally, I have implemented the key checks for `senderName` and `senderDisplayName`. Those two keys can now be used in the command definitions to limit the usage of command to the specified user(s). This key is a list of users, i. e. even if you want to specify only one user it has to be a list.
```
commands = {
  '^!hug' : {
    'answer'     : '$senderDisplayName gives $arg0s and $arg1s cat a hug.',
    'matchType'  : 'regex',
    'cooldown'   : 10,
    'senderName' : ['catlover', 'kittygirl', 'meowmeow']
  },
```

Last but not least I have changed the `cyrillicToLatin()` routine in such a way that it will only apply when the message contains a mixture of Cyrillic letters and Latin ones so that messages consisting solely of Cyrillic letters will not be affected.

**Comment by weidengeist** [comment]
Fix has been uploaded. I had two evaluations of the `senderName` and `senderDisplayName` in the routine – one for the new name list, one for a string. Looked like I had already implemented that some time ago for strings, forgot about it, implemented it again for lists yesterday, and as both are incompatible with each other, it simply had to fail in any case. m/ Sorry about that.

**Comment by weidengeist** [comment]
I have just uploaded a potential fix. Please test if it works now.
